const locationsList = ["✈️💺 Airplane",
    "🏦💰 Bank",
    "🎰💵 Casino",
    "🦸🦹 Cosplay Convention",
    "🛳🌊 Cruise Ship",
    "🚒🧑‍🚒 Fire Station",
    "⚽️🏟 Football Stadium",
    "🌳🏕 Forest Camp",
    "🏪🛒 Grocery Store",
    "🏥🧑‍⚕️ Hospital",
    "🏨🛏 Hotel",
    "🎞🍿 Cinema",
    "🏛🖼 Museum",
    "⛰🥾 Mountain Hike",
    "🏤📮 Post Office",
    "🚔👮‍♂️ Police Station",
    "🍽👩‍🍳 Restaurant",
    "🏟🎸 Rock Concert",
    "🚄🛤 High-speed Train",
    "🏫🎓 University",
];

const validations = ["😀",
    "⭐️",
    "🍪",
    "🍕",
    "🍓",
    "🥐",
    "🍩",
    "🍦",
    "⚽️",
    "🎷",
    "🧩",
    "🔑",
    "🐶",
    "🦜",
    "🐵",
    "🐬",
    "🐢"];

const players = [
    "🧑‍🚀 Astronaut",
    "🧑‍🌾 Farmer",
    "💂 Guard",
    "🧑‍⚖️ Judge",
    "🧑‍🔧 Mechanic",
    "🧑‍🔬 Scientist",
    "🧑‍🎤 Singer",
    "🧑‍🎓 Student",
    "🧑‍🏫 Teacher",
    "👷 Worker",
];
