const locationsList = ["✈️💺 Airplane",
    "🏦💰 Bank",
    "🎰💵 Casino",
    "🦸🦹 Cosplay Convention",
    "🛳🌊 Cruise Ship",
    "🏝🥥 Desert Island",
    "🚒🧑‍🚒 Fire Station",
    "⚽️🏟 Football Stadium",
    "🌳🏕 Forest Camp",
    "🏪🛒 Grocery Store",
    "🏥🧑‍⚕️ Hospital",
    "🏨🛏 Hotel",
    "🎞🍿 Cinema",
    "🌕🧑‍🚀 Moon Colony",
    "🏛🖼 Museum",
    "⛰🥾 Mountain Hike",
    "🏤📮 Post Office",
    "🚔👮‍♂️ Police Station",
    "🍽👩‍🍳 Restaurant",
    "🏟🎸 Rock Concert",
    "🚄🛤 High-speed Train",
    "🏫🎓 University",
];

const validations = ["😀",
    "⭐️",
    "🍪",
    "🍕",
    "🍓",
    "🍒",
    "🥐",
    "🍩",
    "🍦",
    "⚽️",
    "🎷",
    "🧩",
    "🔑",
    "🦜",
    "🐵",
    "🐬",
    "🐢"];

const players = [
    "🐱 Cat",
    "🐶 Dog",
    "🦊 Fox",
    "🐭 Mouse",
    "🐼 Panda",
    "🐧 Penguin",
    "🐰 Rabbit",
    "🐯 Tiger",
    "🦖 T-Rex",
    "🦉 Owl",
];
